LC3 VM: LC3State Class Reference
LC3State Class Reference
Represents the state of an LC-3 virtual machine.
#include <lc3.hpp>
Public Member Functions
LC3State ()
Constructs a new LC3State object. Initializes registers (PC to 0x3000, COND to FL_ZRO) and sets the VM to running.
~LC3State ()
Destroys the LC3State object.
void load_image (const std::string &filename)
Loads an LC-3 program image into memory.
void run ()
Runs the LC-3 virtual machine until halted. Continuously fetches, decodes, and executes instructions.
void step ()
Executes a single LC-3 instruction. Fetches the instruction at PC, increments PC, and executes the instruction.
std::string disassemble (std::uint16_t address)
Disassembles the instruction at a given memory address. (Currently not implemented)
void disassemble_all ()
Disassembles all instructions in loaded memory segments. (Currently not implemented)
void request_halt ()
Requests the VM to halt execution after the current instruction. Sets the internal running flag to false.
std::uint16_t get_register_value (Registers r) const
Retrieves the value of a specified register. Used for testing purposes.
void set_register_value (Registers r, std::uint16_t value)
Sets the value of a specified register. Used for testing purposes.
void write_memory (std::uint16_t address, std::uint16_t value)
Writes a value to a specified memory address. Used for testing purposes.
std::uint16_t read_memory (std::uint16_t address)
Reads a value from a specified memory address. Used for testing purposes.
Static Public Member Functions
template<unsigned op>
static void ins (LC3State &state, std::uint16_t instr)
Executes a specific LC-3 instruction. This is a template function specialized for each opcode.
static std::uint16_t sign_extend (std::uint16_t x, int bit_count)
Sign-extends a number to 16 bits.
Private Member Functions
void update_flags (std::uint16_t r)
Updates the condition flags (R_COND) based on the value of a register.
Private Attributes
Memory memory
std::array< std::uint16_t, R_COUNT > reg
Array of 16-bit registers. This array holds the values of the 16 registers in the LC-3 architecture. The size of the array is determined by the R_COUNT macro.
bool running
Flag indicating whether the LC-3 VM is currently running.
std::vector< CodeSegment > loaded_code_segments
Stores info about loaded program segments.
Static Private Attributes
static const std::array< void(*)(LC3State &, std::uint16_t), 16 > op_table
Table of function pointers for dispatching LC-3 opcodes. Each entry corresponds to an opcode and points to its handler function.
Detailed Description
Represents the state of an LC-3 virtual machine.
This class holds all components of the LC-3 architecture, including memory, registers, the program counter (PC), and condition flags. It provides methods to load programs, run the VM, step through instructions, and inspect/modify its state.
Definition at line 34 of file lc3.hpp.
Constructor & Destructor Documentation
LC3State()
LC3State::LC3State ()
Constructs a new LC3State object. Initializes registers (PC to 0x3000, COND to FL_ZRO) and sets the VM to running.
Definition at line 249 of file ls3.cpp.
                   : memory(), reg{}, running(true) {
    this->reg[R_PC] = 0x3000;
    this->reg[R_COND] = FL_ZRO;
}
References FL_ZRO, R_COND, R_PC, and reg.
~LC3State()
LC3State::~LC3State ()
Destroys the LC3State object.
Definition at line 254 of file ls3.cpp.
                    {
}
Member Function Documentation
disassemble()
std::string LC3State::disassemble (std::uint16_t address)
Disassembles the instruction at a given memory address. (Currently not implemented)
Parameters
address The memory address of the instruction to disassemble.
Returns
A string representation of the disassembled instruction.
Definition at line 291 of file ls3.cpp.
{
    std::uint16_t instr = memory.read(address);
    std::uint16_t opcode = instr >> 12;
    std::ostringstream oss;
    oss << "0x" << std::nouppercase << std::hex << std::setfill('0') << std::setw(4) << address << ": ";
    switch (opcode) {
        case OP_ADD: {
            std::uint16_t dr = (instr >> 9) & 0x7;
            std::uint16_t sr1 = (instr >> 6) & 0x7;
            oss << "ADD R" << dr << ", R" << sr1 << ", ";
            if ((instr >> 5) & 0x1) {
                std::int16_t imm5 = static_cast<std::int16_t>(sign_extend(instr & 0x1F, 5));
                oss << "#" << std::dec << imm5;
            } else {
                std::uint16_t sr2 = instr & 0x7;
                oss << "R" << sr2;
            }
            break;
        }
        case OP_AND: {
            std::uint16_t dr = (instr >> 9) & 0x7;
            std::uint16_t sr1 = (instr >> 6) & 0x7;
            oss << "AND R" << dr << ", R" << sr1 << ", ";
            if ((instr >> 5) & 0x1) {
                std::int16_t imm5 = static_cast<std::int16_t>(sign_extend(instr & 0x1F, 5));
                oss << "#" << std::dec << imm5;
            } else {
                std::uint16_t sr2 = instr & 0x7;
                oss << "R" << sr2;
            }
            break;
        }
        case OP_NOT: {
            std::uint16_t dr = (instr >> 9) & 0x7;
            std::uint16_t sr = (instr >> 6) & 0x7;
            oss << "NOT R" << dr << ", R" << sr;
            break;
        }
        case OP_BR: {
            std::uint16_t n = (instr >> 11) & 0x1;
            std::uint16_t z = (instr >> 10) & 0x1;
            std::uint16_t p = (instr >> 9) & 0x1;
            std::int16_t pc_offset9 = static_cast<std::int16_t>(sign_extend(instr & 0x1FF, 9));
            oss << "BR" << (n ? "n" : "") << (z ? "z" : "") << (p ? "p" : "") << " 0x" << std::nouppercase << std::hex << std::setfill('0') << std::setw(4) << (address + 1 + pc_offset9);
            break;
        }
        case OP_JMP: {
            std::uint16_t base_r = (instr >> 6) & 0x7;
            if (base_r == 7) {
                 oss << "RET";
            } else {
                 oss << "JMP R" << base_r;
            }
            break;
        }
        case OP_JSR: {
            oss << "JSR ";
            if ((instr >> 11) & 1) {
                std::int16_t pc_offset11 = static_cast<std::int16_t>(sign_extend(instr & 0x7FF, 11));
                oss << "0x" << std::nouppercase << std::hex << std::setfill('0') << std::setw(4) << (address + 1 + pc_offset11);
            } else {
                std::uint16_t base_r = (instr >> 6) & 0x7;
                oss << "R" << base_r;
            }
            break;
        }
        case OP_LD: {
            std::uint16_t dr = (instr >> 9) & 0x7;
            std::int16_t pc_offset9 = static_cast<std::int16_t>(sign_extend(instr & 0x1FF, 9));
            oss << "LD R" << dr << ", 0x" << std::nouppercase << std::hex << std::setfill('0') << std::setw(4) << (address + 1 + pc_offset9);
            break;
        }
        case OP_LDI: {
            std::uint16_t dr = (instr >> 9) & 0x7;
            std::int16_t pc_offset9 = static_cast<std::int16_t>(sign_extend(instr & 0x1FF, 9));
            oss << "LDI R" << dr << ", 0x" << std::nouppercase << std::hex << std::setfill('0') << std::setw(4) << (address + 1 + pc_offset9);
            break;
        }
        case OP_LDR: {
            std::uint16_t dr = (instr >> 9) & 0x7;
            std::uint16_t base_r = (instr >> 6) & 0x7;
            std::int16_t offset6 = static_cast<std::int16_t>(sign_extend(instr & 0x3F, 6));
            oss << "LDR R" << dr << ", R" << base_r << ", #" << std::dec << offset6;
            break;
        }
        case OP_LEA: {
            std::uint16_t dr = (instr >> 9) & 0x7;
            std::int16_t pc_offset9 = static_cast<std::int16_t>(sign_extend(instr & 0x1FF, 9));
            oss << "LEA R" << dr << ", 0x" << std::nouppercase << std::hex << std::setfill('0') << std::setw(4) << (address + 1 + pc_offset9);
            break;
        }
        case OP_ST: {
            std::uint16_t sr = (instr >> 9) & 0x7;
            std::int16_t pc_offset9 = static_cast<std::int16_t>(sign_extend(instr & 0x1FF, 9));
            oss << "ST R" << sr << ", 0x" << std::nouppercase << std::hex << std::setfill('0') << std::setw(4) << (address + 1 + pc_offset9);
            break;
        }
        case OP_STI: {
            std::uint16_t sr = (instr >> 9) & 0x7;
            std::int16_t pc_offset9 = static_cast<std::int16_t>(sign_extend(instr & 0x1FF, 9));
            oss << "STI R" << sr << ", 0x" << std::nouppercase << std::hex << std::setfill('0') << std::setw(4) << (address + 1 + pc_offset9);
            break;
        }
        case OP_STR: {
            std::uint16_t sr = (instr >> 9) & 0x7;
            std::uint16_t base_r = (instr >> 6) & 0x7;
            std::int16_t offset6 = static_cast<std::int16_t>(sign_extend(instr & 0x3F, 6));
            oss << "STR R" << sr << ", R" << base_r << ", #" << std::dec << offset6;
            break;
        }
        case OP_TRAP: {
            oss << "TRAP x" << std::nouppercase << std::hex << std::setfill('0') << std::setw(2) << (instr & 0xFF);
            break;
        }
        case OP_RES:
        case OP_RTI:
        default:
            oss << "BAD OPCODE";
            break;
    }
    return oss.str();
}
References ins(), memory, OP_ADD, OP_AND, OP_BR, OP_JMP, OP_JSR, OP_LD, OP_LDI, OP_LDR, OP_LEA, OP_NOT, OP_RES, OP_RTI, OP_ST, OP_STI, OP_STR, OP_TRAP, Memory::read(), and sign_extend().
Referenced by disassemble_all().
disassemble_all()
void LC3State::disassemble_all ()
Disassembles all instructions in loaded memory segments. (Currently not implemented)
Definition at line 416 of file ls3.cpp.
{
    if (loaded_code_segments.empty()) {
        std::cout << "No program images loaded. Nothing to disassemble." << std::endl;
        return;
    }
    for (const auto& segment : loaded_code_segments) {
        for (std::uint16_t i = 0; i < segment.size; ++i) {
            std::uint16_t current_address = segment.start_address + i;
            std::cout << disassemble(current_address) << std::endl;
        }
    }
}
References disassemble(), ins(), and loaded_code_segments.
Referenced by main().
get_register_value()
std::uint16_t LC3State::get_register_value (Registers r) const inline
Retrieves the value of a specified register. Used for testing purposes.
Parameters
r The register to read (from Registers enum).
Returns
The 16-bit value of the register.
Exceptions
std::out_of_range if the register index is invalid.
Definition at line 123 of file lc3.hpp.
{
            if (r >= R_COUNT) throw std::out_of_range("Register index out of bounds");
            return reg[r];
        }
References R_COUNT, and reg.
ins()
template<unsigned op> void LC3State::ins (LC3State & state, std::uint16_t instr) static
Executes a specific LC-3 instruction. This is a template function specialized for each opcode.
Template Parameters
op The opcode to execute (e.g., OP_ADD, OP_LD).
Parameters
state Reference to the current LC3State.
instr The 16-bit instruction word.
Definition at line 36 of file ls3.cpp.
{
    if (op == OP_BR) {
        std::uint16_t cond_flag_from_instr = (instr >> 9) & 0x7;
        if (cond_flag_from_instr & state.reg[R_COND]) {
            state.reg[R_PC] += sign_extend(instr & 0x1FF, 9);
        }
    }
    else if (op == OP_ADD) {
        std::uint16_t r0 = (instr >> 9) & 0x7;
        std::uint16_t r1 = (instr >> 6) & 0x7;
        std::uint16_t imm_flag = (instr >> 5) & 0x1;
        if (imm_flag) {
            std::uint16_t imm5 = sign_extend(instr & 0x1F, 5);
            state.reg[r0] = state.reg[r1] + imm5;
        } else {
            std::uint16_t r2 = instr & 0x7;
            state.reg[r0] = state.reg[r1] + state.reg[r2];
        }
        state.update_flags(r0);
    }
    else if (op == OP_LD) {
        std::uint16_t r0 = (instr >> 9) & 0x7;
        std::uint16_t pc_offset9 = sign_extend(instr & 0x1FF, 9);
        state.reg[r0] = state.memory.read(state.reg[R_PC] + pc_offset9);
        state.update_flags(r0);
    }
    else if (op == OP_ST) {
        std::uint16_t r0 = (instr >> 9) & 0x7;
        std::uint16_t pc_offset9 = sign_extend(instr & 0x1FF, 9);
        state.memory.write(state.reg[R_PC] + pc_offset9, state.reg[r0]);
    }
    else if (op == OP_JSR) {
        state.reg[R_R7] = state.reg[R_PC];
        std::uint16_t long_flag = (instr >> 11) & 1;
        if (long_flag) {
            std::uint16_t long_pc_offset = sign_extend(instr & 0x7FF, 11);
            state.reg[R_PC] += long_pc_offset;
        } else {
            std::uint16_t r1 = (instr >> 6) & 0x7;
            state.reg[R_PC] = state.reg[r1];
        }
    }
    else if (op == OP_AND) {
        std::uint16_t r0 = (instr >> 9) & 0x7;
        std::uint16_t r1 = (instr >> 6) & 0x7;
        std::uint16_t imm_flag = (instr >> 5) & 0x1;
        if (imm_flag) {
            std::uint16_t imm5 = sign_extend(instr & 0x1F, 5);
            state.reg[r0] = state.reg[r1] & imm5;
        } else {
            std::uint16_t r2 = instr & 0x7;
            state.reg[r0] = state.reg[r1] & state.reg[r2];
        }
        state.update_flags(r0);
    }
    else if (op == OP_LDR) {
        std::uint16_t r0 = (instr >> 9) & 0x7;
        std::uint16_t r1 = (instr >> 6) & 0x7;
        std::uint16_t offset6 = sign_extend(instr & 0x3F, 6);
        state.reg[r0] = state.memory.read(state.reg[r1] + offset6);
        state.update_flags(r0);
    }
    else if (op == OP_STR) {
        std::uint16_t r0 = (instr >> 9) & 0x7;
        std::uint16_t r1 = (instr >> 6) & 0x7;
        std::uint16_t offset6 = sign_extend(instr & 0x3F, 6);
        state.memory.write(state.reg[r1] + offset6, state.reg[r0]);
    }
    else if (op == OP_NOT) {
        std::uint16_t r0 = (instr >> 9) & 0x7;
        std::uint16_t r1 = (instr >> 6) & 0x7;
        state.reg[r0] = ~state.reg[r1];
        state.update_flags(r0);
    }
    else if (op == OP_LDI) {
        std::uint16_t r0 = (instr >> 9) & 0x7;
        std::uint16_t pc_offset9 = sign_extend(instr & 0x1FF, 9);
        std::uint16_t effective_address_location = state.reg[R_PC] + pc_offset9;
        state.reg[r0] = state.memory.read(state.memory.read(effective_address_location));
        state.update_flags(r0);
    }
    else if (op == OP_STI) {
        std::uint16_t r0 = (instr >> 9) & 0x7;
        std::uint16_t pc_offset9 = sign_extend(instr & 0x1FF, 9);
        std::uint16_t effective_address_location = state.reg[R_PC] + pc_offset9;
        state.memory.write(state.memory.read(effective_address_location), state.reg[r0]);
    }
    else if (op == OP_JMP) {
        std::uint16_t r1 = (instr >> 6) & 0x7;
        state.reg[R_PC] = state.reg[r1];
    }
    else if (op == OP_LEA) {
        std::uint16_t r0 = (instr >> 9) & 0x7;
        std::uint16_t pc_offset9 = sign_extend(instr & 0x1FF, 9);
        state.reg[r0] = state.reg[R_PC] + pc_offset9;
        state.update_flags(r0);
    }
    else if (op == OP_TRAP) {
        state.reg[R_R7] = state.reg[R_PC];
        switch (instr & 0xFF) {
            case TRAP_GETC:
                {
                    char c_in = 0;
                    if (read(STDIN_FILENO, &c_in, 1) == 1) {
                        state.reg[R_R0] = static_cast<std::uint16_t>(c_in);
                    }
                }
                state.update_flags(R_R0);
                break;
            case TRAP_OUT:
                std::cout.put(static_cast<char>(state.reg[R_R0]));
                std::cout.flush();
                break;
            case TRAP_PUTS: {
                std::uint16_t current_char_addr = state.reg[R_R0];
                std::uint16_t val = state.memory.read(current_char_addr);
                while (val != 0) {
                    std::cout.put(static_cast<char>(val));
                    current_char_addr++;
                    val = state.memory.read(current_char_addr);
                }
                std::cout.flush();
                break;
            }
            case TRAP_IN: {
                std::cout << "Enter a character: ";
                std::cout.flush();
                char c_in_trap = 0;
                if (read(STDIN_FILENO, &c_in_trap, 1) == 1) {
                    std::cout.put(c_in_trap);
                    std::cout.flush();
                    state.reg[R_R0] = static_cast<std::uint16_t>(c_in_trap);
                }
                state.update_flags(R_R0);
                break;
            }
            case TRAP_PUTSP: {
                std::uint16_t current_addr = state.reg[R_R0];
                std::uint16_t word = state.memory.read(current_addr);
                while (word != 0) {
                    char char1 = word & 0xFF;
                    std::cout.put(char1);
                    char char2 = (word >> 8) & 0xFF;
                    if (char2) {
                        std::cout.put(char2);
                    }
                    current_addr++;
                    word = state.memory.read(current_addr);
                }
                std::cout.flush();
                break;
            }
            case TRAP_HALT:
                std::cout << "HALT" << std::endl;
                state.running = false;
                break;
            default:
                throw std::runtime_error("Unknown TRAP vector: " + std::to_string(instr & 0xFF));
                break;
        }
    }
}
References memory, OP_ADD, OP_AND, OP_BR, OP_JMP, OP_JSR, OP_LD, OP_LDI, OP_LDR, OP_LEA, OP_NOT, OP_ST, OP_STI, OP_STR, OP_TRAP, R_COND, R_PC, R_R0, R_R7, Memory::read(), reg, running, sign_extend(), TRAP_GETC, TRAP_HALT, TRAP_IN, TRAP_OUT, TRAP_PUTS, TRAP_PUTSP, update_flags(), and Memory::write().
Referenced by disassemble(), disassemble_all(), load_image(), and step().
load_image()
void LC3State::load_image (const std::string & filename)
Loads an LC-3 program image into memory.
Parameters
filename The path to the .obj file to load.
Exceptions
std::runtime_error if the file cannot be opened or is malformed.
Definition at line 218 of file ls3.cpp.
{
    std::ifstream file(filename, std::ios::binary);
    if (!file.is_open()) {
        throw std::runtime_error("Failed to open image file: " + filename);
    }
    std::uint16_t origin;
    file.read(reinterpret_cast<char*>(&origin), sizeof(origin));
    if (file.gcount() != sizeof(origin)) {
        throw std::runtime_error("Failed to read origin from image file: " + filename);
    }
    origin = swap16(origin);
    std::uint16_t max_words_to_read = MEMORY_MAX - origin;
    std::vector<std::uint16_t> image_data(max_words_to_read);
    file.read(reinterpret_cast<char*>(image_data.data()), max_words_to_read * sizeof(std::uint16_t));
    size_t words_actually_read = file.gcount() / sizeof(std::uint16_t);
    for (size_t i = 0; i < words_actually_read; ++i) {
        if (origin + i < MEMORY_MAX) {
            this->memory.write(origin + i, swap16(image_data[i]));
        } else {
            throw std::runtime_error("Image too large for memory at specified origin.");
        }
    }
    if (words_actually_read > 0) {
        loaded_code_segments.push_back({origin, static_cast<std::uint16_t>(words_actually_read)});
    }
}
References ins(), loaded_code_segments, memory, MEMORY_MAX, swap16(), and Memory::write().
Referenced by main().
read_memory()
std::uint16_t LC3State::read_memory (std::uint16_t address) inline
Reads a value from a specified memory address. Used for testing purposes.
Parameters
address The memory address to read from.
Returns
The 16-bit value at the specified address.
Definition at line 153 of file lc3.hpp.
                                                     { // Added for completeness
            return memory.read(address);
        }
References memory, and Memory::read().
request_halt()
void LC3State::request_halt () inline
Requests the VM to halt execution after the current instruction. Sets the internal running flag to false.
Definition at line 113 of file lc3.hpp.
{ running = false; }
References running.
Referenced by handle_sigint().
run()
void LC3State::run ()
Runs the LC-3 virtual machine until halted. Continuously fetches, decodes, and executes instructions.
Definition at line 257 of file ls3.cpp.
                   {
    this->running = true;
    while (this->running) {
        step();
    }
}
References running, and step().
Referenced by main().
set_register_value()
void LC3State::set_register_value (Registers r, std::uint16_t value) inline
Sets the value of a specified register. Used for testing purposes.
Parameters
r The register to write to (from Registers enum).
value The 16-bit value to set.
Exceptions
std::out_of_range if the register index is invalid.
Definition at line 134 of file lc3.hpp.
{
            if (r >= R_COUNT) throw std::out_of_range("Register index out of bounds");
            reg[r] = value;
        }
References R_COUNT, and reg.
sign_extend()
static std::uint16_t LC3State::sign_extend (std::uint16_t x, int bit_count) inline static
Sign-extends a number to 16 bits.
Parameters
x The number to sign-extend.
bit_count The number of bits in the original number (e.g., 5 for IMM5, 9 for PCoffset9).
Returns
The 16-bit sign-extended value.
Definition at line 163 of file lc3.hpp.
{
            if ((x >> (bit_count - 1)) & 1) {
                x |= (0xFFFF << bit_count);
            }
            return x;
        }
Referenced by disassemble(), and ins().
step()
void LC3State::step ()
Executes a single LC-3 instruction. Fetches the instruction at PC, increments PC, and executes the instruction.
Exceptions
std::runtime_error if an illegal or unsupported opcode is encountered.
Definition at line 264 of file ls3.cpp.
                    {
    if (!this->running) return;
    std::uint16_t current_pc = this->reg[R_PC];
    this->reg[R_PC]++;
    std::uint16_t instruction = this->memory.read(current_pc);
    std::uint16_t opcode_val = instruction >> 12;
    if (opcode_val >= op_table.size() || !op_table[opcode_val]) {
        throw std::runtime_error("Illegal or unsupported opcode: " + std::to_string(opcode_val) +
                                 " at PC: " + std::to_string(current_pc));
    }
    op_table[opcode_val](*this, instruction);
}
References ins(), memory, op_table, R_PC, Memory::read(), reg, and running.
Referenced by run().
update_flags()
void LC3State::update_flags (std::uint16_t r) private
Updates the condition flags (R_COND) based on the value of a register.
Parameters
r The index of the register whose value will be used to set the condition flags. It is expected to be one of the general-purpose registers (R0-R7).
Definition at line 281 of file ls3.cpp.
{
    if (this->reg[r_idx] == 0) {
        this->reg[R_COND] = FL_ZRO;
    } else if (this->reg[r_idx] >> 15) {
        this->reg[R_COND] = FL_NEG;
    } else {
        this->reg[R_COND] = FL_POS;
    }
}
References FL_NEG, FL_POS, FL_ZRO, R_COND, and reg.
Referenced by ins().
write_memory()
void LC3State::write_memory (std::uint16_t address, std::uint16_t value) inline
Writes a value to a specified memory address. Used for testing purposes.
Parameters
address The memory address to write to.
value The 16-bit value to write.
Definition at line 144 of file lc3.hpp.
{
            memory.write(address, value);
        }
References memory, and Memory::write().
Member Data Documentation
loaded_code_segments
std::vector<CodeSegment> LC3State::loaded_code_segments private
Stores info about loaded program segments.
Definition at line 52 of file lc3.hpp.
Referenced by disassemble_all(), and load_image().
memory
Memory LC3State::memory private
Definition at line 36 of file lc3.hpp.
Referenced by disassemble(), ins(), load_image(), read_memory(), step(), and write_memory().
op_table
const std::array< void(*)(LC3State &, std::uint16_t), 16 > LC3State::op_table static private
Initial value:
= {
    [](LC3State& s, std::uint16_t i){ LC3State::ins<OP_BR>(s,i); },
    [](LC3State& s, std::uint16_t i){ LC3State::ins<OP_ADD>(s,i); },
    [](LC3State& s, std::uint16_t i){ LC3State::ins<OP_LD>(s,i); },
    [](LC3State& s, std::uint16_t i){ LC3State::ins<OP_ST>(s,i); },
    [](LC3State& s, std::uint16_t i){ LC3State::ins<OP_JSR>(s,i); },
    [](LC3State& s, std::uint16_t i){ LC3State::ins<OP_AND>(s,i); },
    [](LC3State& s, std::uint16_t i){ LC3State::ins<OP_LDR>(s,i); },
    [](LC3State& s, std::uint16_t i){ LC3State::ins<OP_STR>(s,i); },
    nullptr,
    [](LC3State& s, std::uint16_t i){ LC3State::ins<OP_NOT>(s,i); },
    [](LC3State& s, std::uint16_t i){ LC3State::ins<OP_LDI>(s,i); },
    [](LC3State& s, std::uint16_t i){ LC3State::ins<OP_STI>(s,i); },
    [](LC3State& s, std::uint16_t i){ LC3State::ins<OP_JMP>(s,i); },
    nullptr,
    [](LC3State& s, std::uint16_t i){ LC3State::ins<OP_LEA>(s,i); },
    [](LC3State& s, std::uint16_t i){ LC3State::ins<OP_TRAP>(s,i); }
}
Table of function pointers for dispatching LC-3 opcodes. Each entry corresponds to an opcode and points to its handler function.
Definition at line 199 of file lc3.hpp.
                   {
    std::uint16_t start_address;
    std::uint16_t size;
};
class LC3State {
    private:
        Memory memory;
        std::array<std::uint16_t, R_COUNT> reg;
        void update_flags(std::uint16_t r);
        bool running;
        std::vector<CodeSegment> loaded_code_segments;
        static const std::array<void(*)(LC3State&, std::uint16_t), 16> op_table;
    public:
        template <unsigned op>
        static void ins(LC3State& state, std::uint16_t instr);
        LC3State();
        ~LC3State();
        void load_image(const std::string& filename);
        void run();
        void step();
        std::string disassemble(std::uint16_t address);
        void disassemble_all();
        void request_halt() { running = false; }
        // Test helper methods
        std::uint16_t get_register_value(Registers r) const {
            if (r >= R_COUNT) throw std::out_of_range("Register index out of bounds");
            return reg[r];
        }
        void set_register_value(Registers r, std::uint16_t value) {
            if (r >= R_COUNT) throw std::out_of_range("Register index out of bounds");
            reg[r] = value;
        }
        void write_memory(std::uint16_t address, std::uint16_t value) {
            memory.write(address, value);
        }
        std::uint16_t read_memory(std::uint16_t address) { // Added for completeness
            return memory.read(address);
        }
        static std::uint16_t sign_extend(std::uint16_t x, int bit_count) {
            if ((x >> (bit_count - 1)) & 1) {
                x |= (0xFFFF << bit_count);
            }
            return x;
        }
};
#endif // LC3_H
Referenced by step().
reg
std::array<std::uint16_t, R_COUNT> LC3State::reg private
Array of 16-bit registers. This array holds the values of the 16 registers in the LC-3 architecture. The size of the array is determined by the R_COUNT macro.
Definition at line 42 of file lc3.hpp.
Referenced by get_register_value(), ins(), LC3State(), set_register_value(), step(), and update_flags().
running
bool LC3State::running private
Flag indicating whether the LC-3 VM is currently running.
Definition at line 50 of file lc3.hpp.
Referenced by ins(), request_halt(), run(), and step().
The documentation for this class was generated from the following files:
lc3.hpp
ls3.cpp