LC3 VM: Memory Class Reference
Memory Class Reference
Represents the memory unit of the LC-3 VM.
#include <memory.hpp>
Public Member Functions
std::uint16_t read (std::uint16_t address)
Reads a 16-bit word from the specified memory address. Handles memory-mapped I/O for keyboard status (MR_KBSR) and data (MR_KBDR) registers.
void write (std::uint16_t address, std::uint16_t value)
Writes a 16-bit word to the specified memory address.
Public Attributes
std::uint16_t memory [MEMORY_MAX]
The main memory array. Stores 65536 16-bit words.
Detailed Description
Represents the memory unit of the LC-3 VM.
This class manages the 65536 x 16-bit word addressable memory space. It provides methods for reading from and writing to memory, and handles memory-mapped I/O like keyboard status and data registers.
Definition at line 20 of file memory.hpp.
Member Function Documentation
read()
std::uint16_t Memory::read (std::uint16_t address)
Reads a 16-bit word from the specified memory address. Handles memory-mapped I/O for keyboard status (MR_KBSR) and data (MR_KBDR) registers.
Parameters
address The 16-bit memory address to read from.
Returns
The 16-bit value stored at the given address.
See also
MR_KBSR, MR_KBDR
Definition at line 32 of file memory.cpp.
{
    if (address == Keyboard::MR_KBSR) {
        if (check_key()) {
            memory[Keyboard::MR_KBSR] = (1 << 15);
            char c_in;
            std::cin.get(c_in);
            memory[Keyboard::MR_KBDR] = static_cast<std::uint16_t>(c_in);
        } else {
            memory[Keyboard::MR_KBSR] = 0;
        }
    }
    return memory[address];
}
References check_key(), memory, MR_KBDR, and MR_KBSR.
Referenced by LC3State::disassemble(), LC3State::ins(), LC3State::read_memory(), and LC3State::step().
write()
void Memory::write (std::uint16_t address, std::uint16_t value)
Writes a 16-bit word to the specified memory address.
Parameters
address The 16-bit memory address to write to.
value The 16-bit value to write.
Definition at line 16 of file memory.cpp.
{
    memory[address] = value;
}
References memory.
Referenced by LC3State::ins(), LC3State::load_image(), and LC3State::write_memory().
Member Data Documentation
memory
std::uint16_t Memory::memory[MEMORY_MAX]
The main memory array. Stores 65536 16-bit words.
Definition at line 26 of file memory.hpp.
Referenced by read(), and write().
The documentation for this class was generated from the following files:
memory.hpp
memory.cpp