LC3 VM: terminal_input.hpp File Reference
terminal_input.hpp File Reference
Provides functions to control terminal input mode (raw/canonical).
Functions
void enable_raw_mode ()
Enables raw mode for terminal input. This disables echo, canonical mode, and other terminal features to allow for direct character input.
void disable_raw_mode ()
Disables raw mode and restores original terminal settings. This should be called before the program exits to ensure the terminal is left in a usable state.
bool is_raw_mode_enabled ()
Checks if raw mode is currently enabled.
Detailed Description
Provides functions to control terminal input mode (raw/canonical).
Definition in file terminal_input.hpp.
Function Documentation
disable_raw_mode()
void disable_raw_mode ()
Disables raw mode and restores original terminal settings. This should be called before the program exits to ensure the terminal is left in a usable state.
Definition at line 34 of file terminal_input.cpp.
{
    if (raw_mode_enabled) {
        if (tcsetattr(STDIN_FILENO, TCSAFLUSH, &original_termios) == -1) {
            perror("disable_raw_mode: tcsetattr");
        }
        raw_mode_enabled = false;
    }
}
References original_termios, and raw_mode_enabled.
Referenced by handle_sigint(), and main().
enable_raw_mode()
void enable_raw_mode ()
Enables raw mode for terminal input. This disables echo, canonical mode, and other terminal features to allow for direct character input.
Exceptions
std::runtime_error if terminal attributes cannot be modified.
Definition at line 10 of file terminal_input.cpp.
                       {
    if (tcgetattr(STDIN_FILENO, &original_termios) == -1) {
        perror("tcgetattr");
        throw std::runtime_error("Failed to get terminal attributes.");
    }
    struct termios raw = original_termios;
    raw.c_iflag &= ~(BRKINT | INPCK | ISTRIP | IXON);
    raw.c_cflag |= (CS8);
    raw.c_lflag &= ~(ECHO | ICANON | IEXTEN);
    raw.c_cc[VMIN] = 1;
    raw.c_cc[VTIME] = 0;
    if (tcsetattr(STDIN_FILENO, TCSAFLUSH, &raw) == -1) {
        perror("tcsetattr");
        throw std::runtime_error("Failed to set terminal to raw mode.");
    }
    raw_mode_enabled = true;
}
References original_termios, and raw_mode_enabled.
Referenced by main().
is_raw_mode_enabled()
bool is_raw_mode_enabled ()
Checks if raw mode is currently enabled.
Returns
true if raw mode is enabled, false otherwise.
Definition at line 43 of file terminal_input.cpp.
{
    return raw_mode_enabled;
}
References raw_mode_enabled.